import { normalizeTrait, rollEquipmentTrait } from './equipment-traits.js';
export const RARITY = Object.freeze({ COMMON:'common', UNCOMMON:'uncommon', RARE:'rare', EPIC:'epic', LEGENDARY:'legendary' });
export const RARITY_LABEL = Object.freeze({ common:'普通', uncommon:'上質', rare:'希少', epic:'英雄', legendary:'伝説' });
const item = (id,type,name,price,baseStats,rarity,tier,recommendedLevel,seriesId,shop=true) => Object.freeze({id,type,name,price,baseStats,bonuses:baseStats,rarity,tier,recommendedLevel,seriesId,shop});
export const ITEMS = Object.freeze([
  item('rusty-sword','weapon','錆びた剣',80,{atk:4},RARITY.COMMON,1,1,'standard-sword'), item('iron-sword','weapon','鉄の剣',220,{atk:9},RARITY.UNCOMMON,2,11,'standard-sword'), item('steel-sword','weapon','鋼の剣',520,{atk:16},RARITY.RARE,3,31,'standard-sword'), item('mithril-sword','weapon','ミスリル剣',1080,{atk:23,spd:3},RARITY.EPIC,4,61,'standard-sword'),
  item('small-knife','weapon','小刀',90,{atk:3,spd:3},RARITY.COMMON,1,1,'speed-blade'), item('dagger','weapon','疾風の短剣',350,{atk:8,spd:6},RARITY.RARE,2,16,'speed-blade'), item('gale-knife','weapon','風走りの刃',620,{atk:12,spd:10,def:-2},RARITY.RARE,3,34,'speed-blade'),
  item('old-staff','weapon','古い観察杖',95,{atk:2,obs:4},RARITY.COMMON,1,1,'seer-staff'), item('seer-blade','weapon','観測者の細杖',420,{atk:8,obs:7},RARITY.RARE,2,18,'seer-staff'), item('sage-staff','weapon','賢者の杖',720,{atk:11,obs:13},RARITY.EPIC,3,38,'seer-staff'),
  item('steel-greatsword','weapon','鋼の大剣',480,{atk:17,spd:-3},RARITY.RARE,3,31,'greatsword'), item('abyss-edge','weapon','深淵の曲刀',980,{atk:25,spd:7,def:-3},RARITY.EPIC,4,61,'abyss',false),
  item('leather-armor','armor','革の鎧',100,{def:5,maxHp:10},RARITY.COMMON,1,1,'heavy-armor'), item('iron-armor','armor','鉄の鎧',280,{def:12,maxHp:25,spd:-3},RARITY.UNCOMMON,2,11,'heavy-armor'), item('steel-armor','armor','鋼の鎧',560,{def:19,maxHp:42,spd:-5},RARITY.RARE,3,31,'heavy-armor'), item('sentinel-mail','armor','番人の装甲',1050,{def:28,maxHp:70,spd:-7},RARITY.EPIC,4,61,'heavy-armor'),
  item('light-clothes','armor','探索者の軽装',120,{def:3,spd:4},RARITY.COMMON,1,1,'light-armor'), item('scout-gear','armor','斥候の軽装',330,{def:6,spd:6,obs:7},RARITY.RARE,2,16,'light-armor'), item('shadow-cloak','armor','影渡りの外套',650,{def:9,spd:11,obs:8,maxHp:-10},RARITY.EPIC,3,36,'light-armor'),
  item('battle-garb','armor','戦闘衣',300,{atk:3,def:9},RARITY.UNCOMMON,2,14,'battle-garb'), item('ward-coat','armor','演算障壁衣',590,{def:13,maxHp:20,obs:7},RARITY.RARE,3,38,'battle-garb'), item('dragon-scale','armor','竜鱗の戦衣',1180,{atk:7,def:23,maxHp:38},RARITY.LEGENDARY,4,65,'dragon',false),
  item('herb','consumable','回復薬',45,{heal:35},RARITY.COMMON,1,1,'potion'), item('mid-potion','consumable','中級回復薬',80,{heal:60},RARITY.COMMON,1,6,'potion'), item('high-potion','consumable','上級回復薬',110,{heal:90},RARITY.UNCOMMON,2,11,'potion'), item('deep-potion','consumable','深層回復薬',220,{heal:180},RARITY.RARE,3,31,'potion'), item('elixir','consumable','生命の霊薬',420,{heal:360},RARITY.EPIC,4,61,'potion'),
]);
export const itemById=id=>ITEMS.find(x=>x.id===id);
export const shopTier=floor=>floor<=10?1:floor<=30?2:floor<=60?3:4;
export const initialShopProgress=()=>Object.fromEntries([...new Set(ITEMS.filter(x=>x.shop).map(x=>x.seriesId))].map(id=>[id,0]));
export function shopItems(floor,progress={}){const cap=shopTier(floor);return ITEMS.filter(x=>x.shop&&x.tier<=cap&&x.tier<=(progress[x.seriesId]||0)+1)}
export function createOwnedItem(def,rng,{instanceId,source='shop',rolled=source==='drop',acquiredAt=instanceId,trait}={}){const rolledStats={};for(const [stat,value] of Object.entries(def.baseStats)){const variance=rolled&&value!==0?.9+rng.next()*.2:1;rolledStats[stat]=Math.sign(value)*Math.max(1,Math.round(Math.abs(value)*variance))}const equipment=['weapon','armor'].includes(def.type);const resolvedTrait=trait===undefined&&source==='drop'&&equipment?rollEquipmentTrait(rng):normalizeTrait(trait);return{instanceId,definitionId:def.id,rolledStats,trait:resolvedTrait,acquiredFrom:source,acquiredAt}}
const rarityWeights={normal:[72,21,6,1,0],elite:[25,38,27,9,1],aberrant:[5,20,40,27,8]},rarityOrder=Object.values(RARITY);
function weightedIndex(weights,rng){let roll=rng.next()*weights.reduce((a,b)=>a+b,0);for(let i=0;i<weights.length;i++){roll-=weights[i];if(roll<0)return i}return weights.length-1}
export function rollDrop(enemy,floor,rng,nextInstanceId){const rank=enemy.rank||(enemy.elite?'elite':'normal'),chance=rank==='aberrant'?.95:rank==='elite'?.5:Math.min(.12,.05+enemy.archetype.danger*.035);if(rng.next()>=chance)return null;let tier=shopTier(floor);if(enemy.level>floor*1.3&&rng.next()<.45)tier=Math.min(4,tier+1);if(rank==='aberrant'&&rng.next()<.55)tier=Math.min(4,tier+1);const rarity=rarityOrder[weightedIndex(rarityWeights[rank],rng)];let pool=ITEMS.filter(x=>x.tier===tier&&x.rarity===rarity);if(!pool.length)pool=ITEMS.filter(x=>x.tier===tier&&['weapon','armor','consumable'].includes(x.type));return createOwnedItem(rng.pick(pool),rng,{instanceId:`item-${nextInstanceId}`,source:'drop',rolled:true})}
export function describeBonuses(bonuses){const labels={atk:'ATK',def:'DEF',maxHp:'HP',spd:'SPD',obs:'OBS',heal:'HP回復'};return Object.entries(bonuses).map(([key,value])=>`${labels[key]} ${value>=0?'+':''}${value}`).join(' / ')}
